/**
 * generated by Xtext
 */
package org.xtext.example.xpath.validation;

import org.xtext.example.xpath.validation.AbstractXPathValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class XPathValidator extends AbstractXPathValidator {
}
