/*
 * generated by Xtext
 */
package org.xtext.example.xpath.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XPathUiModule extends org.xtext.example.xpath.ui.AbstractXPathUiModule {
	public XPathUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
