/*
* generated by Xtext
*/
package org.xtext.example.xpath.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.xpath.services.XPathGrammarAccess;

public class XPathParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XPathGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	
	@Override
	protected org.xtext.example.xpath.parser.antlr.internal.InternalXPathParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.xpath.parser.antlr.internal.InternalXPathParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Xpath";
	}
	
	public XPathGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XPathGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
