/*
 * generated by Xtext
 */
package org.xtext.example.xpath.ui.contentassist

import org.xtext.example.xpath.ui.contentassist.AbstractXPathProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class XPathProposalProvider extends AbstractXPathProposalProvider {
}
