/*
 * generated by Xtext
 */
package org.xtext.example.xpath;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XPathRuntimeModule extends org.xtext.example.xpath.AbstractXPathRuntimeModule {

}
