/*
* generated by Xtext
*/
package org.xtext.example.xpath;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XPathStandaloneSetup extends XPathStandaloneSetupGenerated{

	public static void doSetup() {
		new XPathStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

