/*
* generated by Xtext
*/
package org.xtext.example.xpath;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class XPathUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.example.xpath.ui.internal.XPathActivator.getInstance().getInjector("org.xtext.example.xpath.XPath");
	}
	
}
